### PR TITLE
Feature/addthis jumborefresh

### PR DESCRIPTION
**Pull request by jylinman**
Jumbo counter doesn't update like the buttons even though everything else does.  The Jumbo counter updates with the layer refresh, so I added that one line into the repo.

### CODE REVIEW

**Comment by eopa** [comment]
@jylinman thanks for bringing this to our attention, could you update the tests so the build passes?

Also there's no need to commit the files in the `dist/` folder, these will be updated when we push a new release.

**Comment by jylinman** [comment]
@bcmrbvm Sorry for the delay, now the build should be passing.

**Comment by bcmrbvm** [comment]
@jylinman thanks will push a new release soon

**Comment by bcmrbvm** [comment]
@jylinman I've just created a new release: __v0.1.7__ which includes this fix.

**Pull request merged**
